name: R-Type

on:
  pull_request:

env:
  EXECUTABLES: "pbrain-gomoku-ai"

jobs:
  compilation:
    name: "Compilation"
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compilation
        timeout-minutes: 2
        run: make
      - name: Test executables presence
        run: IFS=',' read -r -a array <<< ${{ env.EXECUTABLES }} ; for value in ${array[@]} ; do find . -executable -name "${value}" | grep -q . || echo "::error title="Executable not found"::${value}" ; done
      - name: Exit if executable not found
        run: IFS=',' read -r -a array <<< ${{ env.EXECUTABLES }} ; for value in ${array[@]} ; do find . -executable -name "${value}" | grep -q . || exit 1 ; done

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Install clippy
        run: rustup component add clippy
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clippy check
        run: cargo clippy --fix ; git diff --exit-code

  format:
    name: "Format"
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - name: Install fmt
        run: rustup component add rustfmt
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Format check
        run: cargo fmt --check

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    container: rust:latest
    needs:
      - compilation
      - clippy
      - format
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tests
        timeout-minutes: 2
        run: make tests_run
